name: buddytech
description: "Aplicação BuddyTech – MVP com Login via Supabase."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^6.0.0
  file_picker: ^8.0.0
  http: ^1.2.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# -------------------------------------------------
#   Flutter Launcher Icons Configuration
# -------------------------------------------------
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon.png

  # Fundo sólido azul
  adaptive_icon_background: "#005BEA"

  adaptive_icon_foreground: assets/icon.png

  min_sdk_android: 21


flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/.env
    - assets/icon.png
